### ISSUE TITLE
Question, pods support?

### ISSUE THREAD

**Issue by Panman82** [trentmwillis/ember-css-routes#2]
Quick question, does your addon support the pods structure? So instead of having sub-folders in the styles folder, they are moved to the related pod folder. For example, instead of:

```
-- controllers/
 |- foobar.js
-- routes/
 |- foobar.js
-- styles/
 |- foobar.css
-- templates/
 |- foobar.hbs
```

Pods would be:

```
-- foobar/
 |- controller.js
 |- route.js
 |- styles.css
 |- template.hbs
```

**Comment by trentmwillis** [comment]
Not currently as this structure is really only supported by ember-component-CSS. If it becomes a more common use case, I might add it

**Comment by Panman82** [comment]
I was wondering if that addon would work, but the components folder is still separate from the "routes" folders. Ex:

```
-- components/
 |- foo-baz/
 |  |- component.js
 |  |- styles.css
 |  |- template.hbs
-- foobar/
 |- controller.js
 |- route.js
 |- styles.css ??
 |- template.hbs
```

Note: I still use a "pods" root folder, inside my app.

**Comment by trentmwillis** [comment]
As it currently stands, this add-on won't work with the pods structure because it assumes that stylesheets are located within the `app/styles` directory.

**Comment by Panman82** [comment]
No problem, thought I'd check. It's really a temporary issue anyway, until ember 2.0 with routeable components. At that point I'd assume ember-component-css will work as hoped.
